services:
  memcached:
    image: memcached
    ports:
      - 11211:11211
    entrypoint:
      - memcached
      - -m 64
  easternmind:
    container_name: easternmind
    build: .
    volumes:
      - ./easternmind/config.ini:/easternmind/easternmind/config.ini
      - ./easternmind/db.sqlite3:/easternmind/easternmind/db.sqlite3
      - ./easternmind/media:/easternmind/easternmind/media
    expose:
      - 8000
    links:
      - memcached
    depends_on:
      - memcached
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./easternmind/media/:/web/media/
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
  
