services:
  memcached:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64
  easternmind:
    container_name: easternmind
    build: .
    volumes:
      - ./easternmind/config.ini:/home/easternmind/easternmind/config.ini
      - ./easternmind/db.sqlite3:/home/easternmind/easternmind/db.sqlite3
      - ./easternmind/media:/home/easternmind/easternmind/media
    ports:
      - "8000:8000"
    links:
      - memcached
