# Generated by Django 5.1.1 on 2024-09-27 05:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("image", models.ImageField(upload_to="media/")),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=150)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
