# Generated by Django 5.1.1 on 2024-09-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="format",
            field=models.CharField(
                choices=[(1, "Film"), (2, "Other")], default=1, max_length=10
            ),
        ),
    ]
