# Generated by Django 5.1.1 on 2024-09-27 20:36

import pictures.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_image_format_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=pictures.models.PictureField(
                aspect_ratios=[None],
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                pixel_densities=[1, 2],
                upload_to="",
            ),
        ),
    ]
