# Generated by Django 5.1.1 on 2024-10-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image_picture_height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="image",
            name="image_picture_width",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
