# Generated by Django 5.1.1 on 2024-10-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_image_image_picture_height_image_image_picture_width"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image_picture_height",
            new_name="height_field",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="image_picture_width",
            new_name="width_field",
        ),
    ]
