# Generated by Django 5.1.7 on 2025-04-01 03:31

import pictures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_rename_image_picture_height_image_height_field_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="description",
        ),
        migrations.RemoveField(
            model_name="image",
            name="format",
        ),
        migrations.AlterField(
            model_name="image",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=pictures.models.PictureField(
                aspect_ratios=[None],
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                height_field="height_field",
                pixel_densities=[1, 2],
                upload_to="",
                width_field="width_field",
            ),
        ),
    ]
