# Generated by Django 5.1.7 on 2025-04-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_image_description_remove_image_format_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="format",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
